spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500 # 컬렉션 조회 페이징 및 최적화
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialectContributor
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.CamelCaseToUnderscoresNamingStrategy
    #        use_sql_comments: true
    open-in-view: false

  datasource:
    app:
      driver-class-name: org.postgresql.Driver
      url: ENC(nbd69nrSqB/XNsap0X4BBho5QZ6g5mIOtuT1JZpqgjBAT6rUQ/524zsNqui7r4sY+2pBSGdAgiLsJwdYRW+TBdMDFXfuYqkzsMZ2fl7Nh8fdZWMc/bd5ThOHtQAHOF2u)
      username: ENC(iC7mB1dsNTspESgshgJoIfZxypFH10nD)
      password: ENC(OJ1FF9s7fV9tw8nZ1LrH3e4UXUiWXJzl)
    log:
      driver-class-name: org.postgresql.Driver
      url: ENC(nbd69nrSqB/XNsap0X4BBho5QZ6g5mIOtuT1JZpqgjBAT6rUQ/524zsNqui7r4sY+2pBSGdAgiLsJwdYRW+TBdMDFXfuYqkzsMZ2fl7Nh8fdZWMc/bd5ThOHtQAHOF2u)
      username: ENC(iC7mB1dsNTspESgshgJoIfZxypFH10nD)
      password: ENC(OJ1FF9s7fV9tw8nZ1LrH3e4UXUiWXJzl)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
    org:springframework.security: debug
#aes:
#  secret-key: ENC(fTa2qwMWVDf6dh0nqBhfE6tGobUjdmvFk0DQux6Ap1xnZW2Ym0R7NCgc2oqU26y0)

cloud:
  aws:
    s3:
      bucket: my-taste
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

jwt:
  token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 604800
  secret-key: 06sDw3XXOU2H+v31crClj5OLMnuJJjgAVgiw7l0kU3L6vH7lDxSUlTaqXfaagLFgLHYQH7G+090= # dev
#  secret-key: fExwY7yGgErM6kYNpqKd6q0u6jBuXDBn2ElcC/DRKHnWqiG2KNB7aHabQACPL4lISdexMlyH7RM= # prod
